### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by dtsunam** [sphinx-doc/sphinxcontrib-websupport#66]
sphinxcontrib-websupport seems to depend on sqlalchemy, but it isn't installed when I add sphinxcontrib-websupport to my requirements.txt. I added SQLAlchemy to the requirements.txt but now I see this error when trying to build the docs

```
.venv/lib/python3.12/site-packages/sphinxcontrib/websupport/storage/sqlalchemy_db.py", line 12, in <module>
    from sqlalchemy.orm import relation, sessionmaker, aliased
ImportError: cannot import name 'relation' from 'sqlalchemy.orm' 
```

What are the correct dependencies? Is python 3.12.1 supported?

**Comment by shimizukawa** [comment]
@dtsunam please use "sqlalchemy<2".

SQLAlchemy was significantly changed in 1.4 and some signatures are no longer available in 2.0.
https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4_51/lib/sqlalchemy/orm/__init__.py#L143-L145

Also sphinxcontrib-websupport has not been maintained for a long time and does not keep up with the latest peripheral libraries.
Therefore, it is not known if it will work with Python-3.12.
